name: Build and Push ARM64 Docker Image to OCI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

   
      - name: Login to OCI Container Registry
        uses: docker/login-action@v2
        with:
          registry: ord.ocir.io
          username: ${{ secrets.OCI_USERNAME }}
          password: ${{ secrets.OCI_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Java project with Maven
        run: mvn -Pnative -DskipTests package

      - name: Build and Push ARM64 Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ord.ocir.io/idi1o0a010nx/javademodevops:${{ github.sha }}
          platforms: linux/arm64

      - name: Update k8s Manifest
        env:
          IMAGE_TAG: ${{ github.sha }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          sed "s/\${IMAGE_TAG}/${IMAGE_TAG}/g" deployment-template.yaml > deploy/deployment.yaml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add deploy/deployment.yaml
          git commit -m "Update deployment to SHA ${IMAGE_TAG}"
          git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@https://github.com/josenetoo/java-sample-app-devopsheroes-arm.git HEAD:main
